# Generated by Django 3.1 on 2020-08-30 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "can_create_users_for_his_branch",
                        "Can create users for his branch",
                    ),
                    (
                        "can_create_users_for_his_company",
                        "Can create users for his company",
                    ),
                ]
            },
        ),
    ]
