# Generated by Django 3.1 on 2020-08-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_create_user_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "can_create_users_for_his_branch",
                        "Can create users for his branch",
                    ),
                    (
                        "can_create_users_for_his_company",
                        "Can create users for his company on any branch",
                    ),
                ]
            },
        ),
    ]
