# Generated by Django 3.1 on 2020-08-28 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branches", "0003_userbranch"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserBranch",
            new_name="BranchUser",
        ),
        migrations.AlterUniqueTogether(
            name="branchuser",
            unique_together={("branch", "user")},
        ),
        migrations.AlterModelTable(
            name="branchuser",
            table="branch_users",
        ),
    ]
