# Generated by Django 3.1 on 2020-08-29 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0004_auto_20200828_2206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
