# Generated by Django 3.1 on 2020-08-31 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0005_auto_20200829_1400"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBrand",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "company_brands",
                "db_table": "company_brands",
            },
        ),
        migrations.CreateModel(
            name="CompanyItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(max_length=16)),
                ("model", models.CharField(max_length=255)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("category", models.CharField(max_length=255, null=True)),
                ("subcategory", models.CharField(max_length=255, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.companybrand",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_items",
            },
        ),
        migrations.CreateModel(
            name="BranchItemPrice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.companyitem",
                    ),
                ),
            ],
            options={
                "db_table": "branch_item_prices",
            },
        ),
        migrations.AddIndex(
            model_name="companyitem",
            index=models.Index(
                fields=["category", "subcategory"],
                name="company_ite_categor_e052f2_idx",
            ),
        ),
    ]
