# Generated by Django 3.1 on 2020-08-31 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0005_auto_20200829_1400"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Branch Items",
                "db_table": "branch_items",
            },
        ),
        migrations.AlterModelOptions(
            name="companybrand",
            options={"verbose_name_plural": "Company Brands"},
        ),
        migrations.AlterModelOptions(
            name="companyitem",
            options={"verbose_name_plural": "Company Items"},
        ),
        migrations.DeleteModel(
            name="BranchItemPrice",
        ),
        migrations.AddField(
            model_name="branchitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.companyitem"
            ),
        ),
    ]
